### ISSUE TITLE
Broken gyro() fn in release mode

### ISSUE THREAD

**Issue by knoby** [japaric/l3gd20#6]
I'm using this crate in a project and I had problems reading only the gyro data.

I used the example in the f3 crate to examine the problem. I changed the example that only the gyro is read and run the example. 

If I'm compiling the program in debug mode the data is read and the breakpoint for examin the data is reached. If I use the release mode the program stucks in the read function of the spi of the stm32f30x_hal crate. This happens only with gyro() and not with temp() or all().

All the functions are using the same logic. Only the specific call to the generic function read_registers() use a different array length. 

Perhaps the optimization in release mode breaks the code in specific situations.

**Comment by careyk007** [comment]
I was having the same issue and found out that I needed to change the optimization level in `Cargo.toml`:

``` toml
[profile.release]
# default release opt-level is 3
# valid (working) values are 1, 2, and 'z'
# 's' may also be valid, but it broke a different part of my program
opt-level = 'z'
```
